-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1sl1sOp3lw5xramG
CA+iWzNlft/7ZnlpU3OA1CtlCiugCgYIKoZIzj0DAQehRANCAATF34A6fXrATKlH
zaVcDtVu7NkDbWYIk4MK2g4TJWnWjj7px+1sSibhza1CKlEJCpCk5+OKsr7SjtZM
4lBAYhzk
-----END PRIVATE KEY-----